Measure ceph server resources usage during rados-bench

diff --git a/scripts/benchmarks/bench-rados b/scripts/benchmarks/bench-rados
--- a/scripts/benchmarks/bench-rados
+++ b/scripts/benchmarks/bench-rados
@@ -12,12 +12,11 @@ readonly SCRIPT_DIR
 . "$SCRIPT_DIR/common.sh"
 
 # =============== CONFIGURATIONS TO UPDATE ===============
-readonly CEPH_HOST="10.10.1.2" \
-         CEPH_HOST_USER="ljishen" \
-         LOCAL_HOST="ljishen@10.10.1.1"
+readonly CEPH_HOST="10.10.1.4" \
+         CEPH_HOST_USER="ubuntu"
 
-readonly CEPH_HOST_CPU_AFFINITY=96-127 \
-         LOCAL_HOST_CPU_AFFINITY=96-127
+readonly CEPH_HOST_CPU_AFFINITY=0-7 \
+         LOCAL_HOST_CPU_AFFINITY=32-63,96-127
 
 declare -rA LOCAL_CEPH_CONF_OPTIONS=(
   ['ms_async_rdma_device_name']=mlx5_2
@@ -28,25 +27,80 @@ readonly CEPH_HOST_SRC_BUILD_DIR=/mnt/sda8/ceph/build
 
 readonly POOL_NAME=bench_rados \
          NUM_PGS=128 \
-         POOL_SIZE=2 \
-         OBJECT_SIZES=(4KB 16KB 64KB 256KB 1MB 4MB 16MB 64MB)
+         POOL_SIZE=1 \
+         OBJECT_SIZES=(4KB 16KB 64KB 256KB 1MB 4MB 16MB)
 
 readonly ROUNDS_PER_TEST=5 \
          RADOS_BENCH_RUN_LENTH_SECS=20
 # =============== CONFIGURATIONS TO UPDATE ===============
 
 readonly LOCAL_CEPH_CONF_DIR="$DEPLOYMENT_DATA_ROOT"/etc/ceph \
-         OUTPUT_DIR="$PWD"/output
+         OUTPUT_DIR="$PWD"/output \
+         REMOTE_OUTPUT_DIR=/tmp/bench-rados
 mkdir --parents "$LOCAL_CEPH_CONF_DIR" "$OUTPUT_DIR"
+"$SCRIPT_DIR"/parallel-ssh --host "$CEPH_HOST_USER"@"$CEPH_HOST" \
+  mkdir --parents "$REMOTE_OUTPUT_DIR"
 
 if ! common::is_program_installed "sar"; then
   common::err $(( ERR_STATUS_START + 1 )) "Please install sysstat."
 fi
 pkill -TERM --euid "$USER" --exact sar || true
 
+if ! "$SCRIPT_DIR"/parallel-ssh --host "$CEPH_HOST_USER"@"$CEPH_HOST" bash <<< "
+  command -v sar >/dev/null 2>&1 && \
+    (pkill -TERM --euid $CEPH_HOST_USER --exact sar || true)"; then
+  common::err $(( ERR_STATUS_START + 1 )) "Please install sysstat on the ceph host."
+fi
+
 readonly LOCAL_CEPH_SHELL=" \
   ${LOCAL_HOST_CPU_AFFINITY:+taskset --cpu-list $LOCAL_HOST_CPU_AFFINITY} \
   $SCRIPT_DIR/ceph-shell --"
+
+# https://stackoverflow.com/a/61835747/2926646
+is_uint() { case $1 in '' | *[!0-9]* ) return 1;; esac; }
+
+#######################################
+# Count the number of CPUs in a cpu-list string.
+# Arguments:
+#   A cpu-list string as documented for "--cpu-list" used by command taskset,
+#    https://man7.org/linux/man-pages/man1/taskset.1.html#OPTIONS
+# Returns:
+#   The number of CPUs specified by the cpu-list string.
+#######################################
+count_cpus() {
+  trace_off
+
+  local -r cpu_list="$1"
+  local -a components nums
+  local -i idx cpu_count=0
+
+  IFS=',' read -ra components <<< "$cpu_list"
+  for comp in "${components[@]}"; do
+    IFS='-' read -ra nums <<< "$comp"
+    for (( idx = 0; idx < ${#nums[@]}; idx++ )); do
+      if ! is_uint "${nums[idx]}"; then
+        common::err $(( ERR_STATUS_START + 2 )) \
+          "Cpu-list $cpu_list contains non-integer value in '$comp'"
+      fi
+    done
+
+    if (( ${#nums[@]} == 1 )); then      # comp is a single number
+      (( ++cpu_count ))
+    elif (( ${#nums[@]} == 2 )); then    # comp is a range
+      if (( nums[0] > nums[1] )); then
+        common::err $(( ERR_STATUS_START + 2 )) \
+          "Invalid cpu-list in $cpu_list: start > end (start: ${nums[0]}, end: ${nums[1]})"
+      fi
+      (( cpu_count += nums[1] - nums[0] + 1 ))
+    else
+      common::err $(( ERR_STATUS_START + 2 )) "Invalid cpu-list format in $cpu_list"
+    fi
+  done
+
+  echo "$cpu_count"
+
+  trace_resume
+}
 
 launch_ceph_cluster() {
   common::stage "Launch a Ceph cluster on host $CEPH_HOST ..."
@@ -58,15 +112,18 @@ cd "$CEPH_HOST_SRC_BUILD_DIR" \
   && ../src/stop.sh \
   && rm --force --recursive out dev \
   && ulimit -l unlimited \
-  && MON=1 OSD=3 MDS=0 MGR=1 FS=0 RGW=0 \
+  && MON=1 OSD=1 MDS=0 MGR=1 FS=0 RGW=0 NFS=0 \
       ${CEPH_HOST_CPU_AFFINITY:+taskset --cpu-list $CEPH_HOST_CPU_AFFINITY} \
       ../src/vstart.sh \
-      -d -n -x -i "$CEPH_HOST" --without-dashboard --memstore \
-  && scp -C "${SSH_COMM_OPTIONS[@]}" -p \
-      ceph.conf "$LOCAL_HOST":"$LOCAL_CEPH_CONF_DIR"/ceph.conf \
-  && scp -C "${SSH_COMM_OPTIONS[@]}" -p \
-      keyring "$LOCAL_HOST":"$LOCAL_CEPH_CONF_DIR"/ceph.client.admin.keyring
+      -d -n -x -i "$CEPH_HOST" --without-dashboard --memstore
 EOF
+
+  scp -C "${SSH_COMM_OPTIONS[@]}" -p \
+    "$CEPH_HOST_USER"@"$CEPH_HOST":"$CEPH_HOST_SRC_BUILD_DIR"/ceph.conf \
+    "$LOCAL_CEPH_CONF_DIR"/ceph.conf
+  scp -C "${SSH_COMM_OPTIONS[@]}" -p \
+    "$CEPH_HOST_USER"@"$CEPH_HOST":"$CEPH_HOST_SRC_BUILD_DIR"/keyring \
+    "$LOCAL_CEPH_CONF_DIR"/ceph.client.admin.keyring
   trace_off
 }
 
@@ -162,19 +219,34 @@ rados_bench() {
   local -r mode="$1" round_idx="$2" object_size="$3"
 
   common::stage "Start benchmarking of mode $mode ..."
-  INFO_LEVEL=1
+  (( ++INFO_LEVEL ))
 
-  local -r sysstat_file="$OUTPUT_DIR"/sys_activity_"$object_size"_"$mode".dat."$round_idx" \
+  local -r sysstat_file_bench_host="$OUTPUT_DIR"/sys_activity_"$object_size"_"$mode".dat.bench_host."$round_idx" \
+           sysstat_file_ceph_host="$REMOTE_OUTPUT_DIR"/sys_activity_"$object_size"_"$mode".dat.ceph_host."$round_idx" \
            object_size_bytes="$(object_size_bytes "$object_size")"
-  rm --force "$sysstat_file"
 
-  local sar_pid
+  local -i sar_pid_bench_host sar_pid_ceph_host
 
-  common::info "Start system activity collection service at localhost"
+  common::info "Start system activity collection services"
+  (( ++INFO_LEVEL ))
+
+  common::info "for rados-bench host"
   trace_on
-  S_TIME_FORMAT=ISO sar -A -o "$sysstat_file" 2 >/dev/null 2>&1 & sar_pid=$!
+  rm --force "$sysstat_file_bench_host"
+  S_TIME_FORMAT=ISO sar -A -o "$sysstat_file_bench_host" 2 >/dev/null 2>&1 & sar_pid_bench_host=$!
   trace_off
 
+  common::info "for ceph host"
+  common::create_stdout_dup
+  sar_pid_ceph_host="$(
+    "$SCRIPT_DIR"/parallel-ssh --host "$CEPH_HOST_USER"@"$CEPH_HOST" \
+      bash 2>&1 <<EOF | common::to_stdout_dup | tail -n1
+rm --force $sysstat_file_ceph_host
+S_TIME_FORMAT=ISO sar -A -o $sysstat_file_ceph_host 2 >/dev/null 2>&1 & echo \$!
+EOF
+  )"
+
+  (( --INFO_LEVEL ))
   common::info "Run rados bench"
   if [[ "$mode" == "write" ]]; then
     trace_on
@@ -183,7 +255,7 @@ rados_bench() {
       --pool "$POOL_NAME" \
       -b "$object_size_bytes" \
       -O "$object_size_bytes" \
-      --concurrent-ios 256 \
+      --concurrent-ios $(( $(count_cpus "$LOCAL_HOST_CPU_AFFINITY") * 2 )) \
       --show-time \
       --write-object \
       --write-omap \
@@ -195,16 +267,33 @@ rados_bench() {
     $LOCAL_CEPH_SHELL \
       rados bench 99999999 seq \
       --pool "$POOL_NAME" \
-      --concurrent-ios 256 \
+      --concurrent-ios $(( $(count_cpus "$LOCAL_HOST_CPU_AFFINITY") * 2 )) \
       --show-time 2>&1 | tee "$OUTPUT_DIR"/rados_bench_"$object_size"_"$mode".log."$round_idx"
     trace_off
   else
     common::err $(( ERR_STATUS_START + 3 )) "Unsupport rados bench mode: $mode"
   fi
 
-  common::info "Stop system activity collection service at localhost"
+  common::info "Stop system activity collection services"
+  (( ++INFO_LEVEL ))
+
+  common::info "for rados-bench host"
   trace_on
-  kill -INT "$sar_pid"
+  kill -INT "$sar_pid_bench_host"
+  trace_off
+
+  common::info "for ceph host"
+  trace_on
+  "$SCRIPT_DIR"/parallel-ssh --host "$CEPH_HOST_USER"@"$CEPH_HOST" \
+    kill -INT "$sar_pid_ceph_host"
+  trace_off
+
+  (( ++INFO_LEVEL ))
+  common::info "Copy system activity file from ceph host"
+  trace_on
+  scp -C "${SSH_COMM_OPTIONS[@]}" -p \
+    "$CEPH_HOST_USER"@"$CEPH_HOST":"$sysstat_file_ceph_host" \
+    "$OUTPUT_DIR"/"$(basename -- "$sysstat_file_ceph_host")"
   trace_off
 }
 
diff --git a/scripts/ceph-shell b/scripts/ceph-shell
--- a/scripts/ceph-shell
+++ b/scripts/ceph-shell
@@ -31,10 +31,45 @@ if ! [[ -f "$CEPH_KEYRING_FILE" ]]; then
   common::err $(( ERR_STATUS_START + 1 )) "File $CEPH_KEYRING_FILE does not exist."
 fi
 
-
-if ! [[ -f "$CEPH_SHELL_ARG_FILE" ]] \
-  || [[ "$(stat --format=%y "$CEPH_CONF_FILE")" != "$(stat --format=%y "$CEPH_SHELL_ARG_FILE")" ]]; then
+update_ceph_conf() {
+  # Remove the keyring attribute
   sed --in-place '/keyring *= */d' "$CEPH_CONF_FILE"
+
+  # Merge same sections
+  ## vstart.sh in Ceph v16.2.6 generates two [global] sections and cephadm fails on it
+  local ceph_conf_content
+  ceph_conf_content="$(awk '
+    BEGIN { current = "#none#" }
+
+    /^\[[^]]+\][[:blank:]]*$/ {
+      current = $0
+      next
+    }
+
+    !/^[[:blank:]]*$/ {
+      if (sections[current])
+        sections[current] = sections[current]"\n"$0
+      else
+        sections[current] = $0
+    }
+
+    END {
+      print sections["#none#"]
+
+      for (sec in sections) {
+        if (sec == "#none#")
+          continue
+
+        print sec
+        print sections[sec]
+        print ""
+      }
+    }
+  ' "$CEPH_CONF_FILE")"
+  echo "$ceph_conf_content" >"$CEPH_CONF_FILE"
+}
+
+gen_ceph_shell_arg_file() {
   printf -- '--config %s --keyring %s ' \
     "$CEPH_CONF_FILE" "$CEPH_KEYRING_FILE" >"$CEPH_SHELL_ARG_FILE"
 
@@ -109,6 +144,12 @@ if ! [[ -f "$CEPH_SHELL_ARG_FILE" ]] \
   ' "$CEPH_CONF_FILE" >>"$CEPH_SHELL_ARG_FILE"
 
   touch --reference="$CEPH_CONF_FILE" "$CEPH_SHELL_ARG_FILE"
+}
+
+if ! [[ -f "$CEPH_SHELL_ARG_FILE" ]] \
+  || [[ "$(stat --format=%y "$CEPH_CONF_FILE")" != "$(stat --format=%y "$CEPH_SHELL_ARG_FILE")" ]]; then
+  update_ceph_conf
+  gen_ceph_shell_arg_file
 fi
 
 IFS=" " read -ra CEPH_SHELL_ARGS <<< "$(cat "$CEPH_SHELL_ARG_FILE")"
