Add script ceph-deploy

diff --git a/scripts/parallel-cephadm b/scripts/parallel-cephadm
--- a/scripts/parallel-cephadm
+++ b/scripts/parallel-cephadm
@@ -1,8 +1,30 @@
 #!/usr/bin/env bash
+#
+# Require bash version >= 4.4
 
 set -euo pipefail
 
-if [[ "$#" -eq 0 ]]; then
+debug() { printf "\\033[1;30m[DEBUG] %s\\033[0m\\n" "$*"; }
+err() {
+  local -r exit_status="$1"
+  shift
+  printf "\\033[1;31m[ERROR] %s\\033[0m\\n" "$*" >&2
+  exit "$exit_status"
+}
+
+vergte() { printf '%s\n%s' "$1" "$2" | sort -rCV; }
+if ! vergte "${BASH_VERSION%%[^0-9.]*}" "4.4"; then
+  err 1 "Require bash version >= 4.4"
+fi
+
+# https://stackoverflow.com/a/51548669
+shopt -s expand_aliases
+alias trace_on="{ echo; } 2>/dev/null; set -x"
+alias trace_off="{ set +x; } 2>/dev/null"
+export PS4='# ${BASH_SOURCE:-"$0"}:${LINENO} - ${FUNCNAME[0]:+${FUNCNAME[0]}()} > '
+
+
+if (( $# < 1 )); then
   cat <<EOF
 Usage: $0 [OPTIONS] CEPHADM_ARGS
 
@@ -17,60 +39,57 @@ EOF
   exit
 fi
 
-# https://stackoverflow.com/a/51548669
-shopt -s expand_aliases
-alias trace_on="set -x"
-alias trace_off="{ set +x; } 2>/dev/null; echo"
-
-err() {
-  local exit_status="$1"
-  shift
-  printf "\\033[1;31m[ERROR] %s\\033[0m\\n" "$*" >&2
-  exit "$exit_status"
-}
-
-host_params=()
-cephadm_params=()
+HOST_PARAMS=()
+CEPHADM_PARAMS=()
 
 # loop positional params: https://unix.stackexchange.com/a/314041
 for (( idx = 1; idx <= $#; idx++ )); do
   if [[ "${!idx}" == @(-h|-H|--hosts|--host) ]]; then
-    host_params+=("${!idx}")
+    HOST_PARAMS+=("${!idx}")
     (( idx++ ))
-    host_params+=("${!idx}")
+    HOST_PARAMS+=("${!idx}")
     continue
   fi
 
   if [[ "${!idx}" =~ ^(--hosts=|--host=) ]]; then
-    host_params+=("${!idx}")
+    HOST_PARAMS+=("${!idx}")
     continue
   fi
 
-  cephadm_params+=("${!idx}")
+  CEPHADM_PARAMS+=("${!idx}")
 done
 
-# "@Q" quote each parameter: https://lwn.net/Articles/701009/
-printf -v joined '%s, ' "${host_params[@]@Q}"
-echo "[DEBUG] host_params:" "[${joined%, }]"
-printf -v joined '%s, ' "${cephadm_params[@]@Q}"
-echo "[DEBUG] cephadm_params:" "[${joined%, }]"
+print_arr() {
+  local -rn arr=$1
+  local joined
+  # "@Q" quote each parameter: https://lwn.net/Articles/701009/
+  printf -v joined '%s, ' "${arr[@]@Q}"
+  debug "$1:" "[${joined%, }]"
+}
+print_arr HOST_PARAMS
+print_arr CEPHADM_PARAMS
 
-if (( "${#host_params[@]}" )); then
+if (( "${#HOST_PARAMS[@]}" )); then
   if ! command -v "parallel-ssh" >/dev/null 2>&1; then
-    err 1 "Please install parallel-ssh"
+    err 2 "Please install parallel-ssh"
   fi
 fi
 
-: "${CEPHADM:="$PWD"/cephadm}"
+readonly DEFAULT_BIN_DIR="$PWD"/cephadm_target/bin
+: "${CEPHADM:="$DEFAULT_BIN_DIR"/cephadm}"
 if ! [[ -x "$CEPHADM" ]]; then
-  echo "[INFO] download cephadm"
+  debug "download cephadm"
   trace_on
-  curl --silent --remote-name --location https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm
-  chmod +x cephadm
+  (
+    mkdir -p "$DEFAULT_BIN_DIR" \
+      && cd "$DEFAULT_BIN_DIR" \
+      && curl --silent --remote-name --location https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm \
+      && chmod +x cephadm
+  )
   trace_off
 fi
 
-if (( "${#host_params[@]}" )); then
+if (( "${#HOST_PARAMS[@]}" )); then
   trace_on
   parallel-ssh \
     -O StrictHostKeyChecking=no \
@@ -81,9 +100,11 @@ if (( "${#host_params[@]}" )); then
     --inline \
     --send-input \
     --print \
-    "${host_params[@]}" \
-    "sudo python3 -u - ${cephadm_params[*]}" < "${CEPHADM}"
+    "${HOST_PARAMS[@]}" \
+    "sudo python3 -u - ${CEPHADM_PARAMS[*]}" < "${CEPHADM}"
   trace_off
 else
-  sudo "$CEPHADM" "${cephadm_params[@]}"
+  trace_on
+  sudo "$CEPHADM" "${CEPHADM_PARAMS[@]}"
+  trace_off
 fi
